bookmark_homepage:
    path:     /
    defaults: { _controller: BookmarkBundle:Bookmark:index }
    
bookmark_add:
    path:     /add
    defaults: { _controller: BookmarkBundle:Bookmark:add }
    
bookmark_show:
    path:     /show/{id}
    defaults: { _controller: BookmarkBundle:Bookmark:show }
    
bookmark_edit:
    path:     /edit/{id}
    defaults: { _controller: BookmarkBundle:Bookmark:edit }
    
bookmark_delete:
    path:     /delete/{id}
    defaults: { _controller: BookmarkBundle:Bookmark:delete }

bookmark_edit_category:
    path:     /edit/{id}/category
    defaults: { _controller: BookmarkBundle:Bookmark:editCategory }